### ISSUE TITLE
Error when account has 2FA turned on

### ISSUE THREAD

**Issue by edalzell** [austenc/statamic-instagram-feed#10]
If the account used has 2FA turned on, an error is thrown:

<img width="599" alt="image" src="https://user-images.githubusercontent.com/6069653/100488556-ca8e2000-30c3-11eb-939d-3824c8037705.png">

**Comment by edalzell** [comment]
I note that the underlying package you use recommends a dummy IG acct.

Likely can close this and suggest this in your docs.

**Comment by austenc** [comment]
Thanks @edalzell! Yeah, you're right about the dummy account thing. I'll leave this open as a reminder to document and encourage that.

**Comment by austenc** [comment]
I added a note about this in the readme. Great point so thanks again for bringing this up!
