### ISSUE TITLE
Glide support for images

### ISSUE THREAD

**Issue by austenc** [austenc/statamic-instagram-feed#4]
Would be great if we could use glide to manipulate (and cache!) some of the images. May not be possible, but worth looking in to.

**Comment by dwainscheeren** [comment]
This would be awesome, got a lot of problems now with using the instagram cdn link directly in my project.

**Comment by austenc** [comment]
@dwainscheeren Will try to look at this soon. In the meantime feel free to submit a PR if you know of a way to get this to work!

**Comment by austenc** [comment]
Unfortunately I don't think this is possible without copying the assets to your own statamic instance. If someone wants to PR this, I'm open to it, but I'm not sure it's within the scope of the addon otherwise.
